name: spectre
version: 0.7.0
author: John McCutchan <john@johnmccutchan.com>
description: Graphics Library
homepage: https://github.com/johnmccutchan/spectre
documentation: http://johnmccutchan.github.io/spectre/
environment:
  sdk: '>=0.5.16'
dependencies:
  asset_pack:
    git: https://github.com/johnmccutchan/asset_pack.git
  logging: any
  polymer: any
  vector_math:
    git: https://github.com/johnmccutchan/vector_math.git
dev_dependencies:
  browser: '>=0.5.16'
  game_loop:
    git: https://github.com/johnmccutchan/game_loop.git
  hop: '>=0.22.2'
  unittest: '>=0.5.16'
