name: spectre
description: Graphics Library
version: 0.5.0
author: John McCutchan <john@johnmccutchan.com>
homepage: https://github.com/johnmccutchan/spectre
dependencies:
  unittest:
    sdk: unittest
  marker_prof:
    git: https://github.com/johnmccutchan/markerprof.git
  handle_system:
    git: https://github.com/johnmccutchan/handlesystem.git
  vector_math:
    git: https://github.com/johnmccutchan/DartVectorMath.git
