name: spectre
description: Graphics Library
version: 0.5.0
author: John McCutchan <john@johnmccutchan.com>
homepage: https://github.com/johnmccutchan/spectre
dependencies:
  unittest:
    sdk: unittest
  markerprof:
    git: https://github.com/johnmccutchan/markerprof.git
  handlesystem:
    git: https://github.com/johnmccutchan/handlesystem.git
  dartvectormath:
    git: https://github.com/johnmccutchan/DartVectorMath.git
