name: spectre
description: Graphics Library
version: 0.5.0
author: John McCutchan <john@johnmccutchan.com>
homepage: https://github.com/johnmccutchan/spectre
dependencies:
  marker_prof:
    git: https://github.com/johnmccutchan/markerprof.git
  vector_math:
    git: https://github.com/johnmccutchan/DartVectorMath.git
  game_loop:
    git: https://github.com/johnmccutchan/game_loop.git
  asset_pack:
    git: https://github.com/johnmccutchan/asset_pack.git
  property_map:
    git: git://github.com/financeCoding/property_map.git
  unittest: '>=0.4.1 <0.4.2'
  browser: '>=0.4.1 <0.4.2'
  bot: '>=0.15.0 <0.16.0'
  meta: '>=0.4.1 <0.4.2'
  html5lib: '>=0.4.0 <0.4.1'
  args: '>=0.4.1 <0.4.2'
  logging: '>=0.4.1 <0.4.2'
  pathos: '>=0.4.1 <0.4.2'
  source_maps: '>=0.4.0 <0.4.1'
