name: spectre
version: 0.7.0
author: John McCutchan <john@johnmccutchan.com>
description: Graphics Library
homepage: https://github.com/johnmccutchan/spectre
documentation: http://johnmccutchan.github.io/spectre/
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  asset_pack:
    git: https://github.com/johnmccutchan/asset_pack.git
  logging: '>=0.9.0 <0.10.0'
  polymer: '>=0.9.0 <0.10.0'
  path: '>=0.9.0 <0.10.0'
  vector_math:
    git: https://github.com/johnmccutchan/vector_math.git
dev_dependencies:
  browser: '>=0.9.0 <0.10.0'
  game_loop:
    git: https://github.com/johnmccutchan/game_loop.git
  hop: '>=0.28.1+2'
  unittest: '>=0.9.0 <0.10.0'
